API-PATIENT/src/Entity/Patient.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use JMS\Serializer\Annotation\Type;


/**
 * @ORM\Entity(repositoryClass="App\Repository\PatientRepository")
 */
class Patient
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=40)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=191)
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=191)
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=191)
     */
    private $address;

    /**
     * @ORM\Column(type="integer")
     */
    private $age;

    /**
     * @ORM\Column(type="boolean")
     */
    private $sexe;

    /**
     * @ORM\Column(type="string", length=40)
     */
    private $phone;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_inscription;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getAge(): ?int
    {
        return $this->age;
    }

    public function setAge(int $age): self
    {
        $this->age = $age;

        return $this;
    }

    public function getSexe(): ?bool
    {
        return $this->sexe;
    }

    public function setSexe(bool $sexe): self
    {
        $this->sexe = $sexe;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(string $phone): self
    {
        $this->phone = $phone;

        return $this;
    }

    public function getDateInscription(): ?\DateTimeInterface
    {
        return $this->date_inscription;
    }

    public function setDateInscription(\DateTimeInterface $date_inscription): self
    {
        $this->date_inscription = $date_inscription;

        return $this;
    }
}

API-PATIENT/src/Form/PatientType.php
<?php

namespace App\Form;

use App\Entity\Patient;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PatientType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name')
            ->add('email')
            ->add('password')
            ->add('address')
            ->add('age')
            ->add('sexe')
            ->add('phone')
            ->add('date_inscription')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Patient::class,
        ]);
    }
}

API-PATIENT/src/Controller/PatientController.php
<?php

namespace App\Controller;

use App\Entity\Patient;
use App\Form\PatientType;
use App\Repository\PatientRepository;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/patient")
 */
class PatientController extends Controller
{
    /**
     * @Route("/", name="patient_index", methods="GET")
     */
    public function indexPatientAction(PatientRepository $patientRepository): Response
    {
        $serializer = $this->get('jms_serializer');
        $data = $serializer->serialize($patientRepository->findAll(), 'json');
        $response = new Response($data);
        $response->headers->set('Content-Type', 'application/json');
        return $response;
    }

    /**
     * @Route("/new", name="patient_new", methods="POST")
     */
    public function newPatientAction(Request $request): Response
    {
         try {
            //On recupère les données depuis le formulaire
            $data = $request->getContent();
            //On les décodent
            $patient = $this->get('jms_serializer')->deserialize($data, 'App\Entity\Patient', 'json');
            //On insert les infos dans la database
            $em = $this->getDoctrine()->getManager();
            $em->persist($patient);
            $em->flush();
            return new Response('', Response::HTTP_CREATED);
        } catch (Excepttion $e) {
                echo 'Exception reçue  : ',  $e->getMessage(), "\n";
        }

    }

    /**
     * @Route("/{id}", name="patient_show", methods="GET")
     */
    public function showPatientAction(Patient $patient): Response
    {
        $serializer = $this->get('jms_serializer');
        $data = $serializer->serialize($patient, 'json');
        $response = new Response($data);
        $response->headers->set('Content-Type', 'application/json');
        return $response;

    }

    /**
     * @Route("/{id}/edit", name="patient_edit", methods="GET|POST")
     */
    public function editPatientAction(Request $request, Patient $patient): Response
    {
        $form = $this->createForm(PatientType::class, $patient);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('patient_edit', ['id' => $patient->getId()]);
        }

        return $this->render('patient/edit.html.twig', [
            'patient' => $patient,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="patient_delete", methods="DELETE")
     */
    public function deletePatientAction(Patient $patient): Response
    {
            $em = $this->getDoctrine()->getManager();
            $em->remove($patient);
            $em->flush();
            return new Response("delete succès", Response::HTTP_ACCEPTED);

    }
}

API-PATIENT/templates/patient/_delete_form.html.twig
<form method="post" action="{{ path('patient_delete', {'id': patient.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ patient.id) }}">
    <button class="btn">Delete</button>
</form>

API-PATIENT/templates/patient/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Patient{% endblock %}

{% block body %}
    <h1>Edit Patient</h1>

    {{ include('patient/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('patient_index') }}">back to list</a>

    {{ include('patient/_delete_form.html.twig') }}
{% endblock %}

API-PATIENT/templates/patient/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Patient index{% endblock %}

{% block body %}
    <h1>Patient index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Email</th>
                <th>Password</th>
                <th>Address</th>
                <th>Age</th>
                <th>Sexe</th>
                <th>Phone</th>
                <th>Date_inscription</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for patient in patients %}
            <tr>
                <td>{{ patient.id }}</td>
                <td>{{ patient.name }}</td>
                <td>{{ patient.email }}</td>
                <td>{{ patient.password }}</td>
                <td>{{ patient.address }}</td>
                <td>{{ patient.age }}</td>
                <td>{{ patient.sexe ? 'Yes' : 'No' }}</td>
                <td>{{ patient.phone }}</td>
                <td>{{ patient.dateInscription ? patient.dateInscription|date('Y-m-d H:i:s') : '' }}</td>
                <td>
                    <a href="{{ path('patient_show', {'id': patient.id}) }}">show</a>
                    <a href="{{ path('patient_edit', {'id': patient.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="10">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('patient_new') }}">Create new</a>
{% endblock %}

API-PATIENT/templates/patient/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Patient{% endblock %}

{% block body %}
    <h1>Create new Patient</h1>

    {{ include('patient/_form.html.twig') }}

    <a href="{{ path('patient_index') }}">back to list</a>
{% endblock %}

API-PATIENT/templates/patient/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Patient{% endblock %}

{% block body %}
    <h1>Patient</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ patient.id }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ patient.name }}</td>
            </tr>
            <tr>
                <th>Email</th>
                <td>{{ patient.email }}</td>
            </tr>
            <tr>
                <th>Password</th>
                <td>{{ patient.password }}</td>
            </tr>
            <tr>
                <th>Address</th>
                <td>{{ patient.address }}</td>
            </tr>
            <tr>
                <th>Age</th>
                <td>{{ patient.age }}</td>
            </tr>
            <tr>
                <th>Sexe</th>
                <td>{{ patient.sexe ? 'Yes' : 'No' }}</td>
            </tr>
            <tr>
                <th>Phone</th>
                <td>{{ patient.phone }}</td>
            </tr>
            <tr>
                <th>Date_inscription</th>
                <td>{{ patient.dateInscription ? patient.dateInscription|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('patient_index') }}">back to list</a>

    <a href="{{ path('patient_edit', {'id': patient.id}) }}">edit</a>

    {{ include('patient/_delete_form.html.twig') }}
{% endblock %}