API-PHARMACIEN/src/Entity/Pharmacien.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use JMS\Serializer\Annotation\Type;


/**
 * @ORM\Entity(repositoryClass="App\Repository\PharmacienRepository")
 */
class Pharmacien
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     */
    private $id_pharmacie;

    /**
     * @ORM\Column(type="integer")
     */
    private $siren;

    /**
     * @ORM\Column(type="string", length=40)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=40)
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=191)
     */
    private $address;

    /**
     * @ORM\Column(type="string", length=40)
     */
    private $phone;

    /**
     * @ORM\Column(type="integer")
     */
    private $id_ville;

    /**
     * @ORM\Column(type="integer")
     */
    private $id_proprietaire;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getIdPharmacie(): ?int
    {
        return $this->id_pharmacie;
    }

    public function setIdPharmacie(int $id_pharmacie): self
    {
        $this->id_pharmacie = $id_pharmacie;

        return $this;
    }

    public function getSiren(): ?int
    {
        return $this->siren;
    }

    public function setSiren(int $siren): self
    {
        $this->siren = $siren;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(string $phone): self
    {
        $this->phone = $phone;

        return $this;
    }

    public function getIdVille(): ?int
    {
        return $this->id_ville;
    }

    public function setIdVille(int $id_ville): self
    {
        $this->id_ville = $id_ville;

        return $this;
    }

    public function getIdProprietaire(): ?int
    {
        return $this->id_proprietaire;
    }

    public function setIdProprietaire(int $id_proprietaire): self
    {
        $this->id_proprietaire = $id_proprietaire;

        return $this;
    }
}

API-PHARMACIEN/src/Form/PharmacienType.php
<?php

namespace App\Form;

use App\Entity\Pharmacien;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PharmacienType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('id_pharmacie')
            ->add('siren')
            ->add('name')
            ->add('email')
            ->add('address')
            ->add('phone')
            ->add('id_ville')
            ->add('id_proprietaire')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Pharmacien::class,
        ]);
    }
}

API-PHARMACIEN/src/Controller/PharmacienController.php
<?php

namespace App\Controller;

use App\Entity\Pharmacien;
use App\Form\PharmacienType;
use App\Repository\PharmacienRepository;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/pharmacien")
 */
class PharmacienController extends Controller
{
    /**
     * @Route("/", name="pharmacien_index", methods="GET")
     */
    public function indexPharmacienAction(PharmacienRepository $pharmacienRepository): Response
    {
        $serializer = $this->get('jms_serializer');
        $data = $serializer->serialize($pharmacienRepository->findAll(), 'json');
        $response = new Response($data);
        $response->headers->set('Content-Type', 'application/json');
		$response->headers->set('Access-Control-Allow-Origin', '*');
        return $response;

    }

    /**
     * @Route("/new", name="pharmacien_new", methods="POST")
     */
    public function newPharmacienAction(Request $request): Response
    {
        try {
            //On recupère les données depuis le formulaire
            $data = $request->getContent();
            //On les décodent
            $pharmacien = $this->get('jms_serializer')->deserialize($data, 'App\Entity\Pharmacien', 'json');
            //On insert les infos dans la database
            $em = $this->getDoctrine()->getManager();
            $em->persist($pharmacien);
            $em->flush();
            return new Response('', Response::HTTP_CREATED);
        } catch (Excepttion $e) {
            echo 'Exception reçue  : ',  $e->getMessage(), "\n";
        }

    }

    /**
     * @Route("/{id}", name="pharmacien_show", methods="GET")
     */
    public function showPharmacienAction(Pharmacien $pharmacien): Response
    {
        $serializer = $this->get('jms_serializer');
        $data = $serializer->serialize($pharmacien, 'json');
        $response = new Response($data);
        $response->headers->set('Content-Type', 'application/json');
		$response->headers->set('Access-Control-Allow-Origin', '*');
        return $response;
    }

    /**
     * @Route("/{id}/edit", name="pharmacien_edit", methods="GET|POST")
     */
    public function editPharmacienAction(Request $request, Pharmacien $pharmacien): Response
    {
        $form = $this->createForm(PharmacienType::class, $pharmacien);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('pharmacien_edit', ['id' => $pharmacien->getId()]);
        }

        return $this->render('pharmacien/edit.html.twig', [
            'pharmacien' => $pharmacien,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="pharmacien_delete", methods="DELETE")
     */
    public function deletePharmacienAction(Pharmacien $pharmacien): Response
    {
            $em = $this->getDoctrine()->getManager();
            $em->remove($pharmacien);
            $em->flush();
            return new Response("delete succès", Response::HTTP_ACCEPTED);

    }
}

API-PHARMACIEN/templates/pharmacien/_delete_form.html.twig
<form method="post" action="{{ path('pharmacien_delete', {'id': pharmacien.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ pharmacien.id) }}">
    <button class="btn">Delete</button>
</form>

API-PHARMACIEN/templates/pharmacien/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Pharmacien{% endblock %}

{% block body %}
    <h1>Edit Pharmacien</h1>

    {{ include('pharmacien/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('pharmacien_index') }}">back to list</a>

    {{ include('pharmacien/_delete_form.html.twig') }}
{% endblock %}

API-PHARMACIEN/templates/pharmacien/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Pharmacien index{% endblock %}

{% block body %}
    <h1>Pharmacien index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Id_pharmacie</th>
                <th>Siren</th>
                <th>Name</th>
                <th>Email</th>
                <th>Address</th>
                <th>Phone</th>
                <th>Id_ville</th>
                <th>Id_proprietaire</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for pharmacien in pharmaciens %}
            <tr>
                <td>{{ pharmacien.id }}</td>
                <td>{{ pharmacien.idPharmacie }}</td>
                <td>{{ pharmacien.siren }}</td>
                <td>{{ pharmacien.name }}</td>
                <td>{{ pharmacien.email }}</td>
                <td>{{ pharmacien.address }}</td>
                <td>{{ pharmacien.phone }}</td>
                <td>{{ pharmacien.idVille }}</td>
                <td>{{ pharmacien.idProprietaire }}</td>
                <td>
                    <a href="{{ path('pharmacien_show', {'id': pharmacien.id}) }}">show</a>
                    <a href="{{ path('pharmacien_edit', {'id': pharmacien.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="10">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('pharmacien_new') }}">Create new</a>
{% endblock %}

API-PHARMACIEN/templates/pharmacien/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Pharmacien{% endblock %}

{% block body %}
    <h1>Create new Pharmacien</h1>

    {{ include('pharmacien/_form.html.twig') }}

    <a href="{{ path('pharmacien_index') }}">back to list</a>
{% endblock %}

API-PHARMACIEN/templates/pharmacien/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Pharmacien{% endblock %}

{% block body %}
    <h1>Pharmacien</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ pharmacien.id }}</td>
            </tr>
            <tr>
                <th>Id_pharmacie</th>
                <td>{{ pharmacien.idPharmacie }}</td>
            </tr>
            <tr>
                <th>Siren</th>
                <td>{{ pharmacien.siren }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ pharmacien.name }}</td>
            </tr>
            <tr>
                <th>Email</th>
                <td>{{ pharmacien.email }}</td>
            </tr>
            <tr>
                <th>Address</th>
                <td>{{ pharmacien.address }}</td>
            </tr>
            <tr>
                <th>Phone</th>
                <td>{{ pharmacien.phone }}</td>
            </tr>
            <tr>
                <th>Id_ville</th>
                <td>{{ pharmacien.idVille }}</td>
            </tr>
            <tr>
                <th>Id_proprietaire</th>
                <td>{{ pharmacien.idProprietaire }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('pharmacien_index') }}">back to list</a>

    <a href="{{ path('pharmacien_edit', {'id': pharmacien.id}) }}">edit</a>

    {{ include('pharmacien/_delete_form.html.twig') }}
{% endblock %}