API-PHARMACIE/src/Entity/Pharmacie.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use JMS\Serializer\Annotation\Type;

/**
 * @ORM\Entity(repositoryClass="App\Repository\PharmacieRepository")
 */
class Pharmacie
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     */
    private $id_ville;

    /**
     * @ORM\Column(type="integer")
     */
    private $id_pharmacien;

    /**
     * @ORM\Column(type="integer")
     */
    private $id_proprietaire;

    /**
     * @ORM\Column(type="string", length=40)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=191)
     */
    private $address;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getIdVille(): ?int
    {
        return $this->id_ville;
    }

    public function setIdVille(int $id_ville): self
    {
        $this->id_ville = $id_ville;

        return $this;
    }

    public function getIdPharmacien(): ?int
    {
        return $this->id_pharmacien;
    }

    public function setIdPharmacien(int $id_pharmacien): self
    {
        $this->id_pharmacien = $id_pharmacien;

        return $this;
    }

    public function getIdProprietaire(): ?int
    {
        return $this->id_proprietaire;
    }

    public function setIdProprietaire(int $id_proprietaire): self
    {
        $this->id_proprietaire = $id_proprietaire;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(string $address): self
    {
        $this->address = $address;

        return $this;
    }
}

API-PHARMACIE/src/Form/PharmacieType.php
<?php

namespace App\Form;

use App\Entity\Pharmacie;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PharmacieType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('id_ville')
            ->add('id_pharmacien')
            ->add('id_proprietaire')
            ->add('name')
            ->add('address')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Pharmacie::class,
        ]);
    }
}

API-PHARMACIE/src/Controller/PharmacieController.php
<?php

namespace App\Controller;

use App\Entity\Pharmacie;
use App\Form\PharmacieType;
use App\Repository\PharmacieRepository;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;

/**
 * @Route("/pharmacie")
 */
class PharmacieController extends Controller
{
    /**
     * @Route("/", name="pharmacie_index", methods="GET")
     */
    public function indexPharmacieAction(PharmacieRepository $pharmacieRepository): Response
    {
         $serializer = $this->get('jms_serializer');
        $data = $serializer->serialize($pharmacieRepository->findAll(), 'json');
        $response = new Response($data);
        $response->headers->set('Content-Type', 'application/json');
        return $response;
    }

    /**
     * @Route("/new", name="pharmacie_new", methods="POST")
     */
    public function newPharmacieAction(Request $request): Response
    {
        try {
        //On recupère les données depuis le formulaire
        $data = $request->getContent();
        //On les décodent
        $pharmacie = $this->get('jms_serializer')->deserialize($data, 'App\Entity\Pharmacie', 'json');
        //On insert les infos dans la database
        $em = $this->getDoctrine()->getManager();
        $em->persist($pharmacie);
        $em->flush();
                return new Response('', Response::HTTP_CREATED);
        } catch (Excepttion $e) {
            echo 'Exception reçue  : ',  $e->getMessage(), "\n";
        }

    }

    /**
     * @Route("/{id}", name="pharmacie_show", methods="GET")
     */
    public function showPharmacieAction(Pharmacie $pharmacie): Response
    {
        $serializer = $this->get('jms_serializer');
        $data = $serializer->serialize($pharmacie, 'json');
        $response = new Response($data);
        $response->headers->set('Content-Type', 'application/json');
        return $response;

    }

    /**
     * @Route("/{id}/edit", name="pharmacie_edit", methods="GET|POST")
     */
    public function editPharmacieAction(Request $request, Pharmacie $pharmacie): Response
    {
        $form = $this->createForm(PharmacieType::class, $pharmacie);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('pharmacie_edit', ['id' => $pharmacie->getId()]);
        }

        return $this->render('pharmacie/edit.html.twig', [
            'pharmacie' => $pharmacie,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="pharmacie_delete", methods="DELETE")
     */
    public function deletePharmacieAction(Pharmacie $pharmacie): Response
    {
            $em = $this->getDoctrine()->getManager();
            $em->remove($pharmacie);
            $em->flush();
            return new Response("delete succès", Response::HTTP_ACCEPTED);

    }
}

API-PHARMACIE/templates/pharmacie/_delete_form.html.twig
<form method="post" action="{{ path('pharmacie_delete', {'id': pharmacie.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ pharmacie.id) }}">
    <button class="btn">Delete</button>
</form>

API-PHARMACIE/templates/pharmacie/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Pharmacie{% endblock %}

{% block body %}
    <h1>Edit Pharmacie</h1>

    {{ include('pharmacie/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('pharmacie_index') }}">back to list</a>

    {{ include('pharmacie/_delete_form.html.twig') }}
{% endblock %}

API-PHARMACIE/templates/pharmacie/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Pharmacie index{% endblock %}

{% block body %}
    <h1>Pharmacie index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Id_ville</th>
                <th>Id_pharmacien</th>
                <th>Id_proprietaire</th>
                <th>Name</th>
                <th>Address</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for pharmacie in pharmacies %}
            <tr>
                <td>{{ pharmacie.id }}</td>
                <td>{{ pharmacie.idVille }}</td>
                <td>{{ pharmacie.idPharmacien }}</td>
                <td>{{ pharmacie.idProprietaire }}</td>
                <td>{{ pharmacie.name }}</td>
                <td>{{ pharmacie.address }}</td>
                <td>
                    <a href="{{ path('pharmacie_show', {'id': pharmacie.id}) }}">show</a>
                    <a href="{{ path('pharmacie_edit', {'id': pharmacie.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="7">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('pharmacie_new') }}">Create new</a>
{% endblock %}

API-PHARMACIE/templates/pharmacie/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Pharmacie{% endblock %}

{% block body %}
    <h1>Create new Pharmacie</h1>

    {{ include('pharmacie/_form.html.twig') }}

    <a href="{{ path('pharmacie_index') }}">back to list</a>
{% endblock %}

API-PHARMACIE/templates/pharmacie/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Pharmacie{% endblock %}

{% block body %}
    <h1>Pharmacie</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ pharmacie.id }}</td>
            </tr>
            <tr>
                <th>Id_ville</th>
                <td>{{ pharmacie.idVille }}</td>
            </tr>
            <tr>
                <th>Id_pharmacien</th>
                <td>{{ pharmacie.idPharmacien }}</td>
            </tr>
            <tr>
                <th>Id_proprietaire</th>
                <td>{{ pharmacie.idProprietaire }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ pharmacie.name }}</td>
            </tr>
            <tr>
                <th>Address</th>
                <td>{{ pharmacie.address }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('pharmacie_index') }}">back to list</a>

    <a href="{{ path('pharmacie_edit', {'id': pharmacie.id}) }}">edit</a>

    {{ include('pharmacie/_delete_form.html.twig') }}
{% endblock %}